= RealWorld App in FeathersJS

I did not manage to get the authentication to work while porting feathers 4.5.11.

I tried copying the chat app as much as possible, but I can't get it to work, it is currently failing with:

....
[1] error: NotAuthenticated: Not authenticated
[1]     at new NotAuthenticated (/home/ciro/git/feathers-realworld-example-app/node_modules/@feathersjs/errors/lib/index.js:93:17)
[1]     at /home/ciro/git/feathers-realworld-example-app/node_modules/@feathersjs/authentication/lib/hooks/authenticate.js:54:19
[1]     at Generator.next (<anonymous>)
[1]     at /home/ciro/git/feathers-realworld-example-app/node_modules/@feathersjs/authentication/lib/hooks/authenticate.js:8:71
[1]     at new Promise (<anonymous>)
[1]     at __awaiter (/home/ciro/git/feathers-realworld-example-app/node_modules/@feathersjs/authentication/lib/hooks/authenticate.js:4:12)
[1]     at Object.<anonymous> (/home/ciro/git/feathers-realworld-example-app/node_modules/@feathersjs/authentication/lib/hooks/authenticate.js:27:25)
[1]     at /home/ciro/git/feathers-realworld-example-app/node_modules/@feathersjs/feathers/node_modules/@feathersjs/commons/lib/hooks.js:116:46
....

after you create an account and login, this fails while fetching articles.

Run:

....
git clone --recursive https://github.com/cirosantilli/feathers-realworld-example-app
cd react-redux-realworld-example-app
npm install
cd ..
npm install
npm start
....

Forked from https://github.com/randyscotsmithey/feathers-realworld-example-app adding:

* a more direct integration with https://github.com/gothinkster/react-redux-realworld-example-app[]:
** `npm start` starts both front and backend properly linked without any further configuration
** clearer deployment instructions on how to extract the final built static components
** later on might add as well:
*** SSR
*** realtime functionality
* port from MongoDB to sequelize because:
** MongoDB has serious licencing burden, and was removed from several convenient distros
** sequelize runs on SQLite locally and on a real database remotelly, which dispenses the need for local server management which is a pain
